version: "2"

linters:
  default: standard
  enable:
    - errorlint
  exclusions:
    rules:
      - linters:
          - staticcheck
        text: "QF100[13]:|ST1005:"

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

run:
  timeout: 5m
